task_type: "PDF_GENERATION"
priority: "HIGH"
description: "Criação de PDF com dieta personalizada e recomendações usando dados coletados"

# Contexto necessário para esta tarefa
required_context:
  - consultation_data
  - user_profile_complete
  - calculated_nutrition_needs
  - dietary_restrictions
  - meal_preferences
  - activity_recommendations

# Ferramentas necessárias
tools_required:
  - llm_direct
  - nutrition_calculator
  - meal_planner
  - pdf_generator
  - json_formatter

# Configurações da tarefa
max_iterations: 6
timeout_seconds: 300
success_criteria:
  json_structure_complete: true
  nutrition_values_calculated: true
  meal_plan_structured: true
  recommendations_included: true
  
# Estratégia de fallback se a tarefa falhar
fallback_strategy: "basic_meal_plan_json"

# Prompts específicos para esta tarefa
specialized_prompts:
  json_generation: |
    Você deve gerar um JSON estruturado com:
    - Plano alimentar completo (café, almoço, jantar, lanches)
    - Valores nutricionais calculados
    - Recomendações de atividade física
    - Orientações específicas baseadas nos dados coletados
    
  meal_planning: |
    Para cada refeição, inclua:
    - Lista de ingredientes com quantidades
    - Valor nutricional (calorias, proteínas, carboidratos, gorduras)
    - Instruções de preparo simplificadas
    - Alternativas e substituições possíveis
    
  recommendations: |
    Inclua recomendações para:
    - Horários das refeições
    - Hidratação adequada
    - Atividades físicas compatíveis com o objetivo
    - Monitoramento de progresso
    - Alertas importantes

# Validações específicas
validation_rules:
  - verify_json_structure
  - validate_nutrition_calculations
  - check_meal_balance
  - ensure_goal_alignment
  - validate_safety_guidelines

# Estrutura do JSON de saída
output_structure:
  personal_info:
    - name
    - age
    - goals
    - restrictions
  nutrition_plan:
    - daily_calories
    - macronutrients
    - meal_schedule
  meal_plans:
    - breakfast
    - lunch
    - dinner
    - snacks
  recommendations:
    - exercise
    - hydration
    - monitoring
    - important_notes
